# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
repository: "fredrikj31/fredrikj31.github.io"

title: Fredrik Johansen
email: fredrik1206@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Fredrik Johansen is a 17 years old software developer who likes to learn and teach code. He writes blog posts about his new findings and code-related things.
twitter_username: fredrikj31
github_username: fredrikj31
minimal_mistakes_skin: dark
search: true

# Build settings
markdown: kramdown
remote_theme: mmistakes/minimal-mistakes
# Outputting
permalink: /:categories/:title/
paginate: 5 # amount of posts to show
paginate_path: /page:num/
timezone: Europe/Copenhagen

title_separator: "|"

logo: "/assets/images/logo.png"

# SEO Related
google_site_verification :

# Analytics
analytics:
  provider               : "google-gtag" # false (default), "google", "google-universal", "google-gtag", "custom"
  google:
    tracking_id          : "UA-161178525-1"
    anonymize_ip         : # true, false (default)

# Comments
comments:
  provider: "utterances"
  utterances:
    theme: "github-dark" # "github-dark"
    issue_term: "title"

include:
  - _pages

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

# Plugins (previously gems:)
plugins:
  - jekyll-remote-theme
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

author:
  name   : "Fredrik Johansen"
  avatar : "https://avatars.githubusercontent.com/u/31306224?s=460&u=d3bf0bdd7b29cc137a3c74472b32726a41c8b8e7&v=4"
  bio    : "I'm just a normal human being, and I like to teach and learn coding."
  links:
    - label: "Website"
      icon: "fas fa-fw fa-link"
      url: "https://fredrikj31.github.io"
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/fredrikj31"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/fredrikj31"
    - label: "Linkedin"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/fredrik-johansen/"

footer:
  links:
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/fredrikj31"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/fredrikj31"

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true
  # _portfolio
  - scope:
      path: ""
      type: portfolio
    values:
      layout: single
      author_profile: false
      share: true

collections:
  portfolio:
    output: true
    permalink: /:collection/:path/

category_archive:
  type: liquid
  path: /blog/categories/
tag_archive:
  type: liquid
  path: /blog/tags/
